name: Build
on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      buildVersion:
        description: 'Build version'
        required: true
env:
  BUILD_VERSION: 0.0.${{ github.event.inputs.buildVersion || github.run_number }}
jobs:
  Generate_dictionaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set build version
        run: scripts/set_build_version

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install Pandoc
        run: sudo apt install -y pandoc

      - name: Install LXML
        run: pip3 install lxml

      - name: Prepare the packages
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Test the packages
        run: npx --no-install lerna run test

      - name: Build the packages
        run: npx --no-install lerna run build
        env:
          MOZILLA_API_KEY: ${{ secrets.MOZILLA_API_KEY }}
          MOZILLA_API_SECRET: ${{ secrets.MOZILLA_API_SECRET }}
