name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Generate_dictionaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install LXML
        run: pip3 install lxml
      - name: Prepare the packages
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Test the packages
        run: npx lerna --no-install run test
