name: Generate and distribute dictionaries
on: [push]
jobs:
  Generate_dictionaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install LXML
        run: pip3 install lxml
      - name: Generate new hunspell dictionaries
        run: cd $GITHUB_WORKSPACE && ./generate.sh
      - name: Run convert_dict and copy bdic file to chrome directory
        run: |
          cd $GITHUB_WORKSPACE && bdic_convert/convert_dict output/dictionaries/Medzuslovjansky_KomboLatinicaKirilica && echo "Successfully generated .bdic file."
          cd $GITHUB_WORKSPACE && mv -f output/dictionaries/Medzuslovjansky_KomboLatinicaKirilica.bdic platforms/chrome/src/ && echo ".bdic file moved successfully."
      - name: Move firefox files to destination
        run: |
          cd $GITHUB_WORKSPACE && cp -rf output/dictionaries/Medzuslovjansky_KomboLatinicaKirilica.aff platforms/firefox/src/dictionaries/ && echo "Firefox .aff file moved."
          cd $GITHUB_WORKSPACE && cp -rf output/dictionaries/Medzuslovjansky_KomboLatinicaKirilica.dic platforms/firefox/src/dictionaries/ && echo "Firefox .dic file moved."
      - name: Detect and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git diff-index --quiet HEAD && echo "No changes." || ( git commit -am "[bot] Automatically generated dictionary files for addons." && git push )
