name: Convert Dictionary to bdic
on: [push]
jobs:
  Run_generate_web_addons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run convert_dict
        run: cd $GITHUB_WORKSPACE && bdic_convert/convert_dict output/dictionaries/Medzuslovjansky_KomboLatinicaKirilica && echo "Successfully generated .bdic file."
      - name: Move bdic to destination
        run: cd $GITHUB_WORKSPACE && mv -f output/dictionaries/Medzuslovjansky_KomboLatinicaKirilica.bdic platforms/chrome/src/ && echo ".bdic file moved successfully."
      - name: Move firefox files to destination
        run: |
          cd $GITHUB_WORKSPACE && mv -f output/dictionaries/Medzuslovjansky_KomboLatinicaKirilica.aff platforms/firefox/src/dictionaries/ && "Firefox .aff file moved."
          cd $GITHUB_WORKSPACE && mv -f output/dictionaries/Medzuslovjansky_KomboLatinicaKirilica.dic platforms/firefox/src/dictionaries/ && "Firefox .dic file moved."
      - name: Detect and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add platforms/chrome/src/Medzuslovjansky_KomboLatinicaKirilica.bdic
          git diff-index --quiet HEAD && echo "No changes." || ( git commit -am "[bot] Automatically generated .bdic file" && git push )
